# Site settings
title: The Portfolio of Adam Noffsinger
email: adam.noffsinger@gmail.com
description: "Product designer and prototyper living in San Francisco."
url: "http://noff.me/"
twitter_username: anoffsinger
github_username:  anoffsinger

# Build settings
markdown: kramdown
theme: minima
permalink: none
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
